// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Clay.OpenApiClient.Routines.Item;
using Soenneker.Clay.OpenApiClient.Routines.Run;
using Soenneker.Clay.OpenApiClient.Routines.RunBatch;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Clay.OpenApiClient.Routines
{
    /// <summary>
    /// Builds and executes requests for operations under \routines
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RoutinesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The run property</summary>
        public global::Soenneker.Clay.OpenApiClient.Routines.Run.RunRequestBuilder Run
        {
            get => new global::Soenneker.Clay.OpenApiClient.Routines.Run.RunRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The runBatch property</summary>
        public global::Soenneker.Clay.OpenApiClient.Routines.RunBatch.RunBatchRequestBuilder RunBatch
        {
            get => new global::Soenneker.Clay.OpenApiClient.Routines.RunBatch.RunBatchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Clay.OpenApiClient.routines.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Clay.OpenApiClient.Routines.Item.WithRoutineItemRequestBuilder"/></returns>
        public global::Soenneker.Clay.OpenApiClient.Routines.Item.WithRoutineItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("routineId", position);
                return new global::Soenneker.Clay.OpenApiClient.Routines.Item.WithRoutineItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Clay.OpenApiClient.Routines.RoutinesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RoutinesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/routines", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Clay.OpenApiClient.Routines.RoutinesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RoutinesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/routines", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
