// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Clay.OpenApiClient.Credits.Balance;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Clay.OpenApiClient.Credits
{
    /// <summary>
    /// Builds and executes requests for operations under \credits
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreditsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The balance property</summary>
        public global::Soenneker.Clay.OpenApiClient.Credits.Balance.BalanceRequestBuilder Balance
        {
            get => new global::Soenneker.Clay.OpenApiClient.Credits.Balance.BalanceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Clay.OpenApiClient.Credits.CreditsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CreditsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/credits", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Clay.OpenApiClient.Credits.CreditsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CreditsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/credits", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
