// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Clay.OpenApiClient.Workflows.Runs.Query;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Clay.OpenApiClient.Workflows.Runs
{
    /// <summary>
    /// Builds and executes requests for operations under \workflows\runs
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RunsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The query property</summary>
        public global::Soenneker.Clay.OpenApiClient.Workflows.Runs.Query.QueryRequestBuilder Query
        {
            get => new global::Soenneker.Clay.OpenApiClient.Workflows.Runs.Query.QueryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Clay.OpenApiClient.Workflows.Runs.RunsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RunsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/workflows/runs", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Clay.OpenApiClient.Workflows.Runs.RunsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RunsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/workflows/runs", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
