// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Clay.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AggregateSelectFn
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "count")]
        #pragma warning disable CS1591
        Count,
        #pragma warning restore CS1591
        [EnumMember(Value = "sum")]
        #pragma warning disable CS1591
        Sum,
        #pragma warning restore CS1591
        [EnumMember(Value = "avg")]
        #pragma warning disable CS1591
        Avg,
        #pragma warning restore CS1591
        [EnumMember(Value = "max")]
        #pragma warning disable CS1591
        Max,
        #pragma warning restore CS1591
        [EnumMember(Value = "min")]
        #pragma warning disable CS1591
        Min,
        #pragma warning restore CS1591
    }
}
