// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Clay.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Clay.OpenApiClient.Models.BatchResultsComplete"/>, <see cref="global::Soenneker.Clay.OpenApiClient.Models.BatchResultsProcessingFailed"/>, <see cref="global::Soenneker.Clay.OpenApiClient.Models.BatchResultsValidationFailed"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BatchResultsTerminal : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Clay.OpenApiClient.Models.BatchResultsComplete"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Clay.OpenApiClient.Models.BatchResultsComplete? BatchResultsComplete { get; set; }
#nullable restore
#else
        public global::Soenneker.Clay.OpenApiClient.Models.BatchResultsComplete BatchResultsComplete { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Clay.OpenApiClient.Models.BatchResultsProcessingFailed"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Clay.OpenApiClient.Models.BatchResultsProcessingFailed? BatchResultsProcessingFailed { get; set; }
#nullable restore
#else
        public global::Soenneker.Clay.OpenApiClient.Models.BatchResultsProcessingFailed BatchResultsProcessingFailed { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Clay.OpenApiClient.Models.BatchResultsValidationFailed"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Clay.OpenApiClient.Models.BatchResultsValidationFailed? BatchResultsValidationFailed { get; set; }
#nullable restore
#else
        public global::Soenneker.Clay.OpenApiClient.Models.BatchResultsValidationFailed BatchResultsValidationFailed { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Clay.OpenApiClient.Models.BatchResultsTerminal"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Clay.OpenApiClient.Models.BatchResultsTerminal CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Clay.OpenApiClient.Models.BatchResultsTerminal();
            if("BatchResultsComplete".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.BatchResultsComplete = new global::Soenneker.Clay.OpenApiClient.Models.BatchResultsComplete();
            }
            else if("BatchResultsProcessingFailed".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.BatchResultsProcessingFailed = new global::Soenneker.Clay.OpenApiClient.Models.BatchResultsProcessingFailed();
            }
            else if("BatchResultsValidationFailed".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.BatchResultsValidationFailed = new global::Soenneker.Clay.OpenApiClient.Models.BatchResultsValidationFailed();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(BatchResultsComplete != null)
            {
                return BatchResultsComplete.GetFieldDeserializers();
            }
            else if(BatchResultsProcessingFailed != null)
            {
                return BatchResultsProcessingFailed.GetFieldDeserializers();
            }
            else if(BatchResultsValidationFailed != null)
            {
                return BatchResultsValidationFailed.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(BatchResultsComplete != null)
            {
                writer.WriteObjectValue<global::Soenneker.Clay.OpenApiClient.Models.BatchResultsComplete>(null, BatchResultsComplete);
            }
            else if(BatchResultsProcessingFailed != null)
            {
                writer.WriteObjectValue<global::Soenneker.Clay.OpenApiClient.Models.BatchResultsProcessingFailed>(null, BatchResultsProcessingFailed);
            }
            else if(BatchResultsValidationFailed != null)
            {
                writer.WriteObjectValue<global::Soenneker.Clay.OpenApiClient.Models.BatchResultsValidationFailed>(null, BatchResultsValidationFailed);
            }
        }
    }
}
#pragma warning restore CS0618
