// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Clay.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateSearchRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The filters property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Clay.OpenApiClient.Models.CreateSearchRequestFiltersProperty? Filters { get; set; }
#nullable restore
#else
        public global::Soenneker.Clay.OpenApiClient.Models.CreateSearchRequestFiltersProperty Filters { get; set; }
#endif
        /// <summary>The source_type property</summary>
        public global::Soenneker.Clay.OpenApiClient.Models.CreateSearchRequestSourceType? SourceType { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Clay.OpenApiClient.Models.CreateSearchRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Clay.OpenApiClient.Models.CreateSearchRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Clay.OpenApiClient.Models.CreateSearchRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "filters", n => { Filters = n.GetObjectValue<global::Soenneker.Clay.OpenApiClient.Models.CreateSearchRequestFiltersProperty>(global::Soenneker.Clay.OpenApiClient.Models.CreateSearchRequestFiltersProperty.CreateFromDiscriminatorValue); } },
                { "source_type", n => { SourceType = n.GetEnumValue<global::Soenneker.Clay.OpenApiClient.Models.CreateSearchRequestSourceType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Clay.OpenApiClient.Models.CreateSearchRequestFiltersProperty>("filters", Filters);
            writer.WriteEnumValue<global::Soenneker.Clay.OpenApiClient.Models.CreateSearchRequestSourceType>("source_type", SourceType);
        }
    }
}
#pragma warning restore CS0618
