// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Clay.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum FilterPredicateOp
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "=")]
        #pragma warning disable CS1591
        Equal,
        #pragma warning restore CS1591
        [EnumMember(Value = "!=")]
        #pragma warning disable CS1591
        ExclamationEqual,
        #pragma warning restore CS1591
        [EnumMember(Value = ">")]
        #pragma warning disable CS1591
        GreaterThan,
        #pragma warning restore CS1591
        [EnumMember(Value = ">=")]
        #pragma warning disable CS1591
        GreaterThanOrEqual,
        #pragma warning restore CS1591
        [EnumMember(Value = "<")]
        #pragma warning disable CS1591
        LessThan,
        #pragma warning restore CS1591
        [EnumMember(Value = "<=")]
        #pragma warning disable CS1591
        LessThanOrEqual,
        #pragma warning restore CS1591
        [EnumMember(Value = "contains")]
        #pragma warning disable CS1591
        Contains,
        #pragma warning restore CS1591
        [EnumMember(Value = "not_contains")]
        #pragma warning disable CS1591
        NotContains,
        #pragma warning restore CS1591
        [EnumMember(Value = "starts_with")]
        #pragma warning disable CS1591
        StartsWith,
        #pragma warning restore CS1591
        [EnumMember(Value = "ends_with")]
        #pragma warning disable CS1591
        EndsWith,
        #pragma warning restore CS1591
        [EnumMember(Value = "in")]
        #pragma warning disable CS1591
        InValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "not_in")]
        #pragma warning disable CS1591
        NotIn,
        #pragma warning restore CS1591
        [EnumMember(Value = "is_empty")]
        #pragma warning disable CS1591
        IsEmpty,
        #pragma warning restore CS1591
        [EnumMember(Value = "is_not_empty")]
        #pragma warning disable CS1591
        IsNotEmpty,
        #pragma warning restore CS1591
    }
}
