// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Clay.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Clay.OpenApiClient.Models.FilterAnd"/>, <see cref="global::Soenneker.Clay.OpenApiClient.Models.FilterNot"/>, <see cref="global::Soenneker.Clay.OpenApiClient.Models.FilterOr"/>, <see cref="global::Soenneker.Clay.OpenApiClient.Models.FilterPredicate"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FilterExpression : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Clay.OpenApiClient.Models.FilterAnd"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Clay.OpenApiClient.Models.FilterAnd? FilterAnd { get; set; }
#nullable restore
#else
        public global::Soenneker.Clay.OpenApiClient.Models.FilterAnd FilterAnd { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Clay.OpenApiClient.Models.FilterNot"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Clay.OpenApiClient.Models.FilterNot? FilterNot { get; set; }
#nullable restore
#else
        public global::Soenneker.Clay.OpenApiClient.Models.FilterNot FilterNot { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Clay.OpenApiClient.Models.FilterOr"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Clay.OpenApiClient.Models.FilterOr? FilterOr { get; set; }
#nullable restore
#else
        public global::Soenneker.Clay.OpenApiClient.Models.FilterOr FilterOr { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Clay.OpenApiClient.Models.FilterPredicate"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Clay.OpenApiClient.Models.FilterPredicate? FilterPredicate { get; set; }
#nullable restore
#else
        public global::Soenneker.Clay.OpenApiClient.Models.FilterPredicate FilterPredicate { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Clay.OpenApiClient.Models.FilterExpression"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Clay.OpenApiClient.Models.FilterExpression CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Clay.OpenApiClient.Models.FilterExpression();
            result.FilterAnd = new global::Soenneker.Clay.OpenApiClient.Models.FilterAnd();
            result.FilterNot = new global::Soenneker.Clay.OpenApiClient.Models.FilterNot();
            result.FilterOr = new global::Soenneker.Clay.OpenApiClient.Models.FilterOr();
            result.FilterPredicate = new global::Soenneker.Clay.OpenApiClient.Models.FilterPredicate();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(FilterAnd != null || FilterNot != null || FilterOr != null || FilterPredicate != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(FilterAnd, FilterNot, FilterOr, FilterPredicate);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Clay.OpenApiClient.Models.FilterAnd>(null, FilterAnd, FilterNot, FilterOr, FilterPredicate);
        }
    }
}
#pragma warning restore CS0618
