// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Clay.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FilterPredicate : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The field property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Field { get; set; }
#nullable restore
#else
        public string Field { get; set; }
#endif
        /// <summary>The op property</summary>
        public global::Soenneker.Clay.OpenApiClient.Models.FilterPredicateOp? Op { get; set; }
        /// <summary>The path property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Path { get; set; }
#nullable restore
#else
        public List<string> Path { get; set; }
#endif
        /// <summary>The value property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Clay.OpenApiClient.Models.FilterPredicateValue? Value { get; set; }
#nullable restore
#else
        public global::Soenneker.Clay.OpenApiClient.Models.FilterPredicateValue Value { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Clay.OpenApiClient.Models.FilterPredicate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Clay.OpenApiClient.Models.FilterPredicate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Clay.OpenApiClient.Models.FilterPredicate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "field", n => { Field = n.GetStringValue(); } },
                { "op", n => { Op = n.GetEnumValue<global::Soenneker.Clay.OpenApiClient.Models.FilterPredicateOp>(); } },
                { "path", n => { Path = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "value", n => { Value = n.GetObjectValue<global::Soenneker.Clay.OpenApiClient.Models.FilterPredicateValue>(global::Soenneker.Clay.OpenApiClient.Models.FilterPredicateValue.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("field", Field);
            writer.WriteEnumValue<global::Soenneker.Clay.OpenApiClient.Models.FilterPredicateOp>("op", Op);
            writer.WriteCollectionOfPrimitiveValues<string>("path", Path);
            writer.WriteObjectValue<global::Soenneker.Clay.OpenApiClient.Models.FilterPredicateValue>("value", Value);
        }
    }
}
#pragma warning restore CS0618
