// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Clay.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum InProgressStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "in_progress")]
        #pragma warning disable CS1591
        InProgress,
        #pragma warning restore CS1591
    }
}
