// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Clay.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NextSearchResultsResponsePeriodQuota : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The limit property</summary>
        public double? Limit { get; set; }
        /// <summary>The remaining property</summary>
        public double? Remaining { get; set; }
        /// <summary>The resets_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResetsAt { get; set; }
#nullable restore
#else
        public string ResetsAt { get; set; }
#endif
        /// <summary>The used property</summary>
        public double? Used { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Clay.OpenApiClient.Models.NextSearchResultsResponsePeriodQuota"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Clay.OpenApiClient.Models.NextSearchResultsResponsePeriodQuota CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Clay.OpenApiClient.Models.NextSearchResultsResponsePeriodQuota();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "limit", n => { Limit = n.GetDoubleValue(); } },
                { "remaining", n => { Remaining = n.GetDoubleValue(); } },
                { "resets_at", n => { ResetsAt = n.GetStringValue(); } },
                { "used", n => { Used = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("limit", Limit);
            writer.WriteDoubleValue("remaining", Remaining);
            writer.WriteStringValue("resets_at", ResetsAt);
            writer.WriteDoubleValue("used", Used);
        }
    }
}
#pragma warning restore CS0618
