// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Clay.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NextQueryModePeopleResultsResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Clay.OpenApiClient.Models.PublicApiPersonSearchResult>? Data { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Clay.OpenApiClient.Models.PublicApiPersonSearchResult> Data { get; set; }
#endif
        /// <summary>The exhaustion_reason property</summary>
        public global::Soenneker.Clay.OpenApiClient.Models.NextQueryModePeopleResultsResponseExhaustionReason? ExhaustionReason { get; set; }
        /// <summary>The has_more property</summary>
        public bool? HasMore { get; set; }
        /// <summary>The period_quota property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Clay.OpenApiClient.Models.NextQueryModePeopleResultsResponsePeriodQuota? PeriodQuota { get; set; }
#nullable restore
#else
        public global::Soenneker.Clay.OpenApiClient.Models.NextQueryModePeopleResultsResponsePeriodQuota PeriodQuota { get; set; }
#endif
        /// <summary>The source_type property</summary>
        public global::Soenneker.Clay.OpenApiClient.Models.PeopleSourceType? SourceType { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Clay.OpenApiClient.Models.NextQueryModePeopleResultsResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Clay.OpenApiClient.Models.NextQueryModePeopleResultsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Clay.OpenApiClient.Models.NextQueryModePeopleResultsResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "data", n => { Data = n.GetCollectionOfObjectValues<global::Soenneker.Clay.OpenApiClient.Models.PublicApiPersonSearchResult>(global::Soenneker.Clay.OpenApiClient.Models.PublicApiPersonSearchResult.CreateFromDiscriminatorValue)?.AsList(); } },
                { "exhaustion_reason", n => { ExhaustionReason = n.GetEnumValue<global::Soenneker.Clay.OpenApiClient.Models.NextQueryModePeopleResultsResponseExhaustionReason>(); } },
                { "has_more", n => { HasMore = n.GetBoolValue(); } },
                { "period_quota", n => { PeriodQuota = n.GetObjectValue<global::Soenneker.Clay.OpenApiClient.Models.NextQueryModePeopleResultsResponsePeriodQuota>(global::Soenneker.Clay.OpenApiClient.Models.NextQueryModePeopleResultsResponsePeriodQuota.CreateFromDiscriminatorValue); } },
                { "source_type", n => { SourceType = n.GetEnumValue<global::Soenneker.Clay.OpenApiClient.Models.PeopleSourceType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Clay.OpenApiClient.Models.PublicApiPersonSearchResult>("data", Data);
            writer.WriteEnumValue<global::Soenneker.Clay.OpenApiClient.Models.NextQueryModePeopleResultsResponseExhaustionReason>("exhaustion_reason", ExhaustionReason);
            writer.WriteBoolValue("has_more", HasMore);
            writer.WriteObjectValue<global::Soenneker.Clay.OpenApiClient.Models.NextQueryModePeopleResultsResponsePeriodQuota>("period_quota", PeriodQuota);
            writer.WriteEnumValue<global::Soenneker.Clay.OpenApiClient.Models.PeopleSourceType>("source_type", SourceType);
        }
    }
}
#pragma warning restore CS0618
