// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Clay.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum NextQueryModePeopleResultsResponseExhaustionReason
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "query_limit")]
        #pragma warning disable CS1591
        QueryLimit,
        #pragma warning restore CS1591
        [EnumMember(Value = "no_more_results")]
        #pragma warning disable CS1591
        NoMoreResults,
        #pragma warning restore CS1591
    }
}
