// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Clay.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PublicApiPersonSearchResult : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The clay_profile_id property</summary>
        public double? ClayProfileId { get; set; }
        /// <summary>The first_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstName { get; set; }
#nullable restore
#else
        public string FirstName { get; set; }
#endif
        /// <summary>The last_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastName { get; set; }
#nullable restore
#else
        public string LastName { get; set; }
#endif
        /// <summary>The location property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Clay.OpenApiClient.Models.PublicApiPersonSearchResultLocation? Location { get; set; }
#nullable restore
#else
        public global::Soenneker.Clay.OpenApiClient.Models.PublicApiPersonSearchResultLocation Location { get; set; }
#endif
        /// <summary>The matched_experiences property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Clay.OpenApiClient.Models.PublicApiMatchedExperience>? MatchedExperiences { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Clay.OpenApiClient.Models.PublicApiMatchedExperience> MatchedExperiences { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Clay.OpenApiClient.Models.PublicApiPersonSearchResult"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Clay.OpenApiClient.Models.PublicApiPersonSearchResult CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Clay.OpenApiClient.Models.PublicApiPersonSearchResult();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "clay_profile_id", n => { ClayProfileId = n.GetDoubleValue(); } },
                { "first_name", n => { FirstName = n.GetStringValue(); } },
                { "last_name", n => { LastName = n.GetStringValue(); } },
                { "location", n => { Location = n.GetObjectValue<global::Soenneker.Clay.OpenApiClient.Models.PublicApiPersonSearchResultLocation>(global::Soenneker.Clay.OpenApiClient.Models.PublicApiPersonSearchResultLocation.CreateFromDiscriminatorValue); } },
                { "matched_experiences", n => { MatchedExperiences = n.GetCollectionOfObjectValues<global::Soenneker.Clay.OpenApiClient.Models.PublicApiMatchedExperience>(global::Soenneker.Clay.OpenApiClient.Models.PublicApiMatchedExperience.CreateFromDiscriminatorValue)?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("clay_profile_id", ClayProfileId);
            writer.WriteStringValue("first_name", FirstName);
            writer.WriteStringValue("last_name", LastName);
            writer.WriteObjectValue<global::Soenneker.Clay.OpenApiClient.Models.PublicApiPersonSearchResultLocation>("location", Location);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Clay.OpenApiClient.Models.PublicApiMatchedExperience>("matched_experiences", MatchedExperiences);
            writer.WriteStringValue("name", Name);
        }
    }
}
#pragma warning restore CS0618
