// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Clay.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class QueryResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The cursor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Cursor { get; set; }
#nullable restore
#else
        public string Cursor { get; set; }
#endif
        /// <summary>The data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Clay.OpenApiClient.Models.QueryResponseDataItemProperty>? Data { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Clay.OpenApiClient.Models.QueryResponseDataItemProperty> Data { get; set; }
#endif
        /// <summary>The fields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Clay.OpenApiClient.Models.QueryResponseFieldsProperty? Fields { get; set; }
#nullable restore
#else
        public global::Soenneker.Clay.OpenApiClient.Models.QueryResponseFieldsProperty Fields { get; set; }
#endif
        /// <summary>True when more results matched than the limit but no cursor can be issued (grouped, aggregated, or custom-ordered queries do not support cursor pagination). Narrow the query or raise the limit to see the rest.</summary>
        public bool? Truncated { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Clay.OpenApiClient.Models.QueryResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Clay.OpenApiClient.Models.QueryResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Clay.OpenApiClient.Models.QueryResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cursor", n => { Cursor = n.GetStringValue(); } },
                { "data", n => { Data = n.GetCollectionOfObjectValues<global::Soenneker.Clay.OpenApiClient.Models.QueryResponseDataItemProperty>(global::Soenneker.Clay.OpenApiClient.Models.QueryResponseDataItemProperty.CreateFromDiscriminatorValue)?.AsList(); } },
                { "fields", n => { Fields = n.GetObjectValue<global::Soenneker.Clay.OpenApiClient.Models.QueryResponseFieldsProperty>(global::Soenneker.Clay.OpenApiClient.Models.QueryResponseFieldsProperty.CreateFromDiscriminatorValue); } },
                { "truncated", n => { Truncated = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("cursor", Cursor);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Clay.OpenApiClient.Models.QueryResponseDataItemProperty>("data", Data);
            writer.WriteObjectValue<global::Soenneker.Clay.OpenApiClient.Models.QueryResponseFieldsProperty>("fields", Fields);
            writer.WriteBoolValue("truncated", Truncated);
        }
    }
}
#pragma warning restore CS0618
