// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Clay.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RunsQueryRow : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The action_credits_used property</summary>
        public double? ActionCreditsUsed { get; set; }
        /// <summary>The created_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>The data_credits_used property</summary>
        public double? DataCreditsUsed { get; set; }
        /// <summary>The ended_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EndedAt { get; set; }
#nullable restore
#else
        public string EndedAt { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The input_field_count property</summary>
        public int? InputFieldCount { get; set; }
        /// <summary>The output_field_count property</summary>
        public int? OutputFieldCount { get; set; }
        /// <summary>The run_status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RunStatus { get; set; }
#nullable restore
#else
        public string RunStatus { get; set; }
#endif
        /// <summary>The started_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartedAt { get; set; }
#nullable restore
#else
        public string StartedAt { get; set; }
#endif
        /// <summary>The trigger_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TriggerId { get; set; }
#nullable restore
#else
        public string TriggerId { get; set; }
#endif
        /// <summary>The workflow_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkflowId { get; set; }
#nullable restore
#else
        public string WorkflowId { get; set; }
#endif
        /// <summary>The workflow_snapshot_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkflowSnapshotId { get; set; }
#nullable restore
#else
        public string WorkflowSnapshotId { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Clay.OpenApiClient.Models.RunsQueryRow"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Clay.OpenApiClient.Models.RunsQueryRow CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Clay.OpenApiClient.Models.RunsQueryRow();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action_credits_used", n => { ActionCreditsUsed = n.GetDoubleValue(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "data_credits_used", n => { DataCreditsUsed = n.GetDoubleValue(); } },
                { "ended_at", n => { EndedAt = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "input_field_count", n => { InputFieldCount = n.GetIntValue(); } },
                { "output_field_count", n => { OutputFieldCount = n.GetIntValue(); } },
                { "run_status", n => { RunStatus = n.GetStringValue(); } },
                { "started_at", n => { StartedAt = n.GetStringValue(); } },
                { "trigger_id", n => { TriggerId = n.GetStringValue(); } },
                { "workflow_id", n => { WorkflowId = n.GetStringValue(); } },
                { "workflow_snapshot_id", n => { WorkflowSnapshotId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("action_credits_used", ActionCreditsUsed);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteDoubleValue("data_credits_used", DataCreditsUsed);
            writer.WriteStringValue("ended_at", EndedAt);
            writer.WriteStringValue("id", Id);
            writer.WriteIntValue("input_field_count", InputFieldCount);
            writer.WriteIntValue("output_field_count", OutputFieldCount);
            writer.WriteStringValue("run_status", RunStatus);
            writer.WriteStringValue("started_at", StartedAt);
            writer.WriteStringValue("trigger_id", TriggerId);
            writer.WriteStringValue("workflow_id", WorkflowId);
            writer.WriteStringValue("workflow_snapshot_id", WorkflowSnapshotId);
        }
    }
}
#pragma warning restore CS0618
