// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Clay.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SearchCreateExample : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The intent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Intent { get; set; }
#nullable restore
#else
        public string Intent { get; set; }
#endif
        /// <summary>The request property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Clay.OpenApiClient.Models.SearchCreateExampleRequest? Request { get; set; }
#nullable restore
#else
        public global::Soenneker.Clay.OpenApiClient.Models.SearchCreateExampleRequest Request { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Clay.OpenApiClient.Models.SearchCreateExample"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Clay.OpenApiClient.Models.SearchCreateExample CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Clay.OpenApiClient.Models.SearchCreateExample();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "intent", n => { Intent = n.GetStringValue(); } },
                { "request", n => { Request = n.GetObjectValue<global::Soenneker.Clay.OpenApiClient.Models.SearchCreateExampleRequest>(global::Soenneker.Clay.OpenApiClient.Models.SearchCreateExampleRequest.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("intent", Intent);
            writer.WriteObjectValue<global::Soenneker.Clay.OpenApiClient.Models.SearchCreateExampleRequest>("request", Request);
        }
    }
}
#pragma warning restore CS0618
