// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Clay.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum StructuredQueryFieldMode
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "names")]
        #pragma warning disable CS1591
        Names,
        #pragma warning restore CS1591
        [EnumMember(Value = "ids")]
        #pragma warning disable CS1591
        Ids,
        #pragma warning restore CS1591
    }
}
