// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Clay.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class StructuredQuery : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The field_mode property</summary>
        public global::Soenneker.Clay.OpenApiClient.Models.StructuredQueryFieldMode? FieldMode { get; set; }
        /// <summary>The filter property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Clay.OpenApiClient.Models.FilterExpression? Filter { get; set; }
#nullable restore
#else
        public global::Soenneker.Clay.OpenApiClient.Models.FilterExpression Filter { get; set; }
#endif
        /// <summary>The group_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? GroupBy { get; set; }
#nullable restore
#else
        public List<string> GroupBy { get; set; }
#endif
        /// <summary>The join property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Clay.OpenApiClient.Models.StructuredQueryJoinItem>? Join { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Clay.OpenApiClient.Models.StructuredQueryJoinItem> Join { get; set; }
#endif
        /// <summary>Custom sort. Queries with a custom order_by do not support cursor pagination.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Clay.OpenApiClient.Models.StructuredQueryOrderByItem>? OrderBy { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Clay.OpenApiClient.Models.StructuredQueryOrderByItem> OrderBy { get; set; }
#endif
        /// <summary>The select property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Clay.OpenApiClient.Models.StructuredQuerySelectItem>? Select { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Clay.OpenApiClient.Models.StructuredQuerySelectItem> Select { get; set; }
#endif
        /// <summary>The tables property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Clay.OpenApiClient.Models.StructuredQueryTablesItem>? Tables { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Clay.OpenApiClient.Models.StructuredQueryTablesItem> Tables { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Clay.OpenApiClient.Models.StructuredQuery"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Clay.OpenApiClient.Models.StructuredQuery CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Clay.OpenApiClient.Models.StructuredQuery();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "field_mode", n => { FieldMode = n.GetEnumValue<global::Soenneker.Clay.OpenApiClient.Models.StructuredQueryFieldMode>(); } },
                { "filter", n => { Filter = n.GetObjectValue<global::Soenneker.Clay.OpenApiClient.Models.FilterExpression>(global::Soenneker.Clay.OpenApiClient.Models.FilterExpression.CreateFromDiscriminatorValue); } },
                { "group_by", n => { GroupBy = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "join", n => { Join = n.GetCollectionOfObjectValues<global::Soenneker.Clay.OpenApiClient.Models.StructuredQueryJoinItem>(global::Soenneker.Clay.OpenApiClient.Models.StructuredQueryJoinItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "order_by", n => { OrderBy = n.GetCollectionOfObjectValues<global::Soenneker.Clay.OpenApiClient.Models.StructuredQueryOrderByItem>(global::Soenneker.Clay.OpenApiClient.Models.StructuredQueryOrderByItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "select", n => { Select = n.GetCollectionOfObjectValues<global::Soenneker.Clay.OpenApiClient.Models.StructuredQuerySelectItem>(global::Soenneker.Clay.OpenApiClient.Models.StructuredQuerySelectItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "tables", n => { Tables = n.GetCollectionOfObjectValues<global::Soenneker.Clay.OpenApiClient.Models.StructuredQueryTablesItem>(global::Soenneker.Clay.OpenApiClient.Models.StructuredQueryTablesItem.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Clay.OpenApiClient.Models.StructuredQueryFieldMode>("field_mode", FieldMode);
            writer.WriteObjectValue<global::Soenneker.Clay.OpenApiClient.Models.FilterExpression>("filter", Filter);
            writer.WriteCollectionOfPrimitiveValues<string>("group_by", GroupBy);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Clay.OpenApiClient.Models.StructuredQueryJoinItem>("join", Join);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Clay.OpenApiClient.Models.StructuredQueryOrderByItem>("order_by", OrderBy);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Clay.OpenApiClient.Models.StructuredQuerySelectItem>("select", Select);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Clay.OpenApiClient.Models.StructuredQueryTablesItem>("tables", Tables);
        }
    }
}
#pragma warning restore CS0618
