// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Clay.OpenApiClient.Routines.Item.RunBatch.Start;
using Soenneker.Clay.OpenApiClient.Routines.Item.RunBatch.UploadUrl;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Clay.OpenApiClient.Routines.Item.RunBatch
{
    /// <summary>
    /// Builds and executes requests for operations under \routines\{routineId}\run-batch
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RunBatchRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The start property</summary>
        public global::Soenneker.Clay.OpenApiClient.Routines.Item.RunBatch.Start.StartRequestBuilder Start
        {
            get => new global::Soenneker.Clay.OpenApiClient.Routines.Item.RunBatch.Start.StartRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The uploadUrl property</summary>
        public global::Soenneker.Clay.OpenApiClient.Routines.Item.RunBatch.UploadUrl.UploadUrlRequestBuilder UploadUrl
        {
            get => new global::Soenneker.Clay.OpenApiClient.Routines.Item.RunBatch.UploadUrl.UploadUrlRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Clay.OpenApiClient.Routines.Item.RunBatch.RunBatchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RunBatchRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/routines/{routineId}/run-batch", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Clay.OpenApiClient.Routines.Item.RunBatch.RunBatchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RunBatchRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/routines/{routineId}/run-batch", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
