// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Clay.OpenApiClient.Search.FiltersMode.Item.Run;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Clay.OpenApiClient.Search.FiltersMode.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \search\filters-mode\{searchId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithSearchItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The run property</summary>
        public global::Soenneker.Clay.OpenApiClient.Search.FiltersMode.Item.Run.RunRequestBuilder Run
        {
            get => new global::Soenneker.Clay.OpenApiClient.Search.FiltersMode.Item.Run.RunRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Clay.OpenApiClient.Search.FiltersMode.Item.WithSearchItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSearchItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/search/filters-mode/{searchId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Clay.OpenApiClient.Search.FiltersMode.Item.WithSearchItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSearchItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/search/filters-mode/{searchId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
