// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using Soenneker.Clay.OpenApiClient.Me;
using Soenneker.Clay.OpenApiClient.Routines;
using Soenneker.Clay.OpenApiClient.Search;
using Soenneker.Clay.OpenApiClient.Tables;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Clay.OpenApiClient
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ClayOpenApiClient : BaseRequestBuilder
    {
        /// <summary>The me property</summary>
        public global::Soenneker.Clay.OpenApiClient.Me.MeRequestBuilder Me
        {
            get => new global::Soenneker.Clay.OpenApiClient.Me.MeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The routines property</summary>
        public global::Soenneker.Clay.OpenApiClient.Routines.RoutinesRequestBuilder Routines
        {
            get => new global::Soenneker.Clay.OpenApiClient.Routines.RoutinesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::Soenneker.Clay.OpenApiClient.Search.SearchRequestBuilder Search
        {
            get => new global::Soenneker.Clay.OpenApiClient.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tables property</summary>
        public global::Soenneker.Clay.OpenApiClient.Tables.TablesRequestBuilder Tables
        {
            get => new global::Soenneker.Clay.OpenApiClient.Tables.TablesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Clay.OpenApiClient.ClayOpenApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ClayOpenApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "https://api.clay.com/public/v0";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
