// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Clay.OpenApiClient.Routines.Item.Run;
using Soenneker.Clay.OpenApiClient.Routines.Item.RunBatch;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Clay.OpenApiClient.Routines.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \routines\{routineId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithRoutineItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The run property</summary>
        public global::Soenneker.Clay.OpenApiClient.Routines.Item.Run.RunRequestBuilder Run
        {
            get => new global::Soenneker.Clay.OpenApiClient.Routines.Item.Run.RunRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The runBatch property</summary>
        public global::Soenneker.Clay.OpenApiClient.Routines.Item.RunBatch.RunBatchRequestBuilder RunBatch
        {
            get => new global::Soenneker.Clay.OpenApiClient.Routines.Item.RunBatch.RunBatchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Clay.OpenApiClient.Routines.Item.WithRoutineItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithRoutineItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/routines/{routineId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Clay.OpenApiClient.Routines.Item.WithRoutineItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithRoutineItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/routines/{routineId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
