// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Clay.OpenApiClient.Routines.RunBatch.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Clay.OpenApiClient.Routines.RunBatch
{
    /// <summary>
    /// Builds and executes requests for operations under \routines\run-batch
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RunBatchRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Clay.OpenApiClient.routines.runBatch.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Clay.OpenApiClient.Routines.RunBatch.Item.WithRoutineRunItemRequestBuilder"/></returns>
        public global::Soenneker.Clay.OpenApiClient.Routines.RunBatch.Item.WithRoutineRunItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("routineRunId", position);
                return new global::Soenneker.Clay.OpenApiClient.Routines.RunBatch.Item.WithRoutineRunItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Clay.OpenApiClient.Routines.RunBatch.RunBatchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RunBatchRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/routines/run-batch", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Clay.OpenApiClient.Routines.RunBatch.RunBatchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RunBatchRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/routines/run-batch", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
